### ISSUE TITLE
Target Netstandard

### ISSUE THREAD

**Issue by spelltwister** [Kevin-Bronsdijk/kraken-net#10]
Hey guys,

I was wondering if it was possible to get a netstandard build packaged for nuget.  Right now, using kraken-net I have to use netstandard2.0 so I can target the existing package.

Thanks!

**Comment by Kevin-Bronsdijk** [comment]
Hi,

I was already planning a release, however, will have to look into the details to see whats required and how much work is involved. 

I've created a new project which can be found here https://github.com/Kevin-Bronsdijk/kraken-net/projects/3. Hopefully, I can look into this next month. 

Regards, 
Kevin

**Comment by spelltwister** [comment]
Sounds good.  I'll probably pull a copy and see what's involved, but all the other stuff I've converted was super simple.  Clearly the code can port as I am using it successfully, but it can probably target a lower standard than 2.0

**Comment by Kevin-Bronsdijk** [comment]
Just an update on this; I've created a branch targetting 1.6 right here
https://github.com/Kevin-Bronsdijk/kraken-net/tree/DotNetStandard

Still need to work on the following items:

- Not sure how to run test from the new test project (not working in VS 2017.1 and Rider)
- Fix CI for the current build
- Put everything together in CI build (not sure how to target all the frameworks)
- Replace System.Drawing.Graphics with an alternative (needed for integration  tests however low priority)

**Comment by Kevin-Bronsdijk** [comment]
Added 1.6 support in pr #13. The package (v 2.0) is available on nuget. Much of the tooling is still not up to standards but will clean up the project later.
