### ISSUE TITLE
Square strategy resize should accept a "size" (instead of width and height)

### ISSUE THREAD

**Issue by karim79** [Kevin-Bronsdijk/kraken-net#2]
Can we fix the square strategy to accept a "size" instead of a width and height? Currently issuing a square strategy request fails since Kraken.io API expects a "size" to be set instead, as per https://kraken.io/docs/image-resizing

"resize": {
    "size": 100,
    "strategy": "square"
}

Thanks!

**Comment by Kevin-Bronsdijk** [comment]
@karim79 Yes, I must have missed that parameter. Will add it right away and release a new version shortly.

**Comment by Kevin-Bronsdijk** [comment]
Version 1.1.4 has been published on Nuget.org 

Package location - https://www.nuget.org/packages/kraken-net/1.1.4
Related tests / sample code - Client_CustomRequestChangeSizeSquare_IsTrue
