### ISSUE TITLE
Custom Image Quality functionality

### ISSUE THREAD

**Issue by pateljan** [Kevin-Bronsdijk/kraken-net#5]
could you Please  update the library to support **Custom Image Quality** feature with Lossy image optimization.? 
As per specified in kraken documentation below.

https://kraken.io/docs/custom-image-quality.

**Comment by Kevin-Bronsdijk** [comment]
Part of PR #6 which you created recently. Changes can me merged after fixing the review comments.

**Comment by Kevin-Bronsdijk** [comment]
Just released the changes you've made. The NuGet package version is 1.1.5. 
Thank you for your contribution.
