### ISSUE TITLE
Strategy enum missing "none"

### ISSUE THREAD

**Issue by michaelTBF** [Kevin-Bronsdijk/kraken-net#8]
https://kraken.io/docs/generating-image-sets#returning-the-optimized-original-size-image - as described here the is a "none" strategy. That is missing in the Enum.

**Comment by Kevin-Bronsdijk** [comment]
You are right, I've added none as an option the PR is #9  Add None as a strategy. New NuGet package will be up soon.

**Comment by Kevin-Bronsdijk** [comment]
https://www.nuget.org/packages/kraken-net/1.1.6
